﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Predictly_Api
{
    public partial class History
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"Father's Highest Education Level", @"Father's Highest Education Level"),new InputOutputColumnPair(@"Mother's Highest Education Level", @"Mother's Highest Education Level"),new InputOutputColumnPair(@"Study Hours", @"Study Hours")})      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(@"Average Previous Marks", @"Average Previous Marks"))      
                                    .Append(mlContext.Transforms.Conversion.ConvertType(@"Class Status", @"Class Status"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Father's Highest Education Level",@"Mother's Highest Education Level",@"Study Hours",@"Average Previous Marks",@"Class Status"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"Actual Result",inputColumnName:@"Actual Result"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.LightGbm(new LightGbmMulticlassTrainer.Options(){NumberOfLeaves=7010,NumberOfIterations=24,MinimumExampleCountPerLeaf=20,LearningRate=0.0242376828277186,LabelColumnName=@"Actual Result",FeatureColumnName=@"Features",ExampleWeightColumnName=null,Booster=new GradientBooster.Options(){SubsampleFraction=0.001074725676671,FeatureFraction=0.695303801700822,L1Regularization=2.54011299160584E-08,L2Regularization=0.000522211596314079},MaximumBinCountPerFeature=435}))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
}
