<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <UserSecretsId>aspnet-Predictly_Api-56B73840-3D93-4E74-9ECF-649683474244</UserSecretsId>
    <RootNamespace>Predictly_Api</RootNamespace>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" Version="3.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="5.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="5.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="5.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Identity.Web" Version="1.1.0" />
    <PackageReference Include="Microsoft.ML" Version="1.7.0" />
    <PackageReference Include="Microsoft.ML.FastTree" Version="1.7.0" />
    <PackageReference Include="Microsoft.ML.LightGbm" Version="1.7.0" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.2.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.2.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="5.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.3.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="5.7.0" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Serilog.AspNetCore" />
    <None Remove="Serilog.Settings.Configuration" />
    <None Remove="Serilog.Sinks.MSSqlServer" />
    <None Remove="ViewModels\Goal\" />
    <None Remove="Filters\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Filters\" />
  </ItemGroup>
  <ItemGroup Label="Mathematics">
    <None Include="Mathematics.consumption.cs">
      <DependentUpon>Mathematics.mbconfig</DependentUpon>
    </None>
    <None Include="Mathematics.training.cs">
      <DependentUpon>Mathematics.mbconfig</DependentUpon>
    </None>
    <None Include="Mathematics.zip">
      <DependentUpon>Mathematics.mbconfig</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup Label="Buddhism">
    <None Include="Buddhism.consumption.cs">
      <DependentUpon>Buddhism.mbconfig</DependentUpon>
    </None>
    <None Include="Buddhism.training.cs">
      <DependentUpon>Buddhism.mbconfig</DependentUpon>
    </None>
    <None Include="Buddhism.zip">
      <DependentUpon>Buddhism.mbconfig</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup Label="Sinhala">
    <None Include="Sinhala.consumption.cs">
      <DependentUpon>Sinhala.mbconfig</DependentUpon>
    </None>
    <None Include="Sinhala.training.cs">
      <DependentUpon>Sinhala.mbconfig</DependentUpon>
    </None>
    <None Include="Sinhala.zip">
      <DependentUpon>Sinhala.mbconfig</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup Label="English">
    <None Include="English.consumption.cs">
      <DependentUpon>English.mbconfig</DependentUpon>
    </None>
    <None Include="English.training.cs">
      <DependentUpon>English.mbconfig</DependentUpon>
    </None>
    <None Include="English.zip">
      <DependentUpon>English.mbconfig</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup Label="History">
    <None Include="History.consumption.cs">
      <DependentUpon>History.mbconfig</DependentUpon>
    </None>
    <None Include="History.training.cs">
      <DependentUpon>History.mbconfig</DependentUpon>
    </None>
    <None Include="History.zip">
      <DependentUpon>History.mbconfig</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup Label="Science">
    <None Include="Science.consumption.cs">
      <DependentUpon>Science.mbconfig</DependentUpon>
    </None>
    <None Include="Science.training.cs">
      <DependentUpon>Science.mbconfig</DependentUpon>
    </None>
    <None Include="Science.zip">
      <DependentUpon>Science.mbconfig</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup Label="Commerce">
    <None Include="Commerce.consumption.cs">
      <DependentUpon>Commerce.mbconfig</DependentUpon>
    </None>
    <None Include="Commerce.training.cs">
      <DependentUpon>Commerce.mbconfig</DependentUpon>
    </None>
    <None Include="Commerce.zip">
      <DependentUpon>Commerce.mbconfig</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup Label="OrientedMusic">
    <None Include="OrientedMusic.consumption.cs">
      <DependentUpon>OrientedMusic.mbconfig</DependentUpon>
    </None>
    <None Include="OrientedMusic.training.cs">
      <DependentUpon>OrientedMusic.mbconfig</DependentUpon>
    </None>
    <None Include="OrientedMusic.zip">
      <DependentUpon>OrientedMusic.mbconfig</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup Label="ICT">
    <None Include="ICT.consumption.cs">
      <DependentUpon>ICT.mbconfig</DependentUpon>
    </None>
    <None Include="ICT.training.cs">
      <DependentUpon>ICT.mbconfig</DependentUpon>
    </None>
    <None Include="ICT.zip">
      <DependentUpon>ICT.mbconfig</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>