// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Predictly_Api
{
    public partial class OrientedMusic
    {
        /// <summary>
        /// model input class for OrientedMusic.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Father's Highest Education Level")]
            public float Father_s_Highest_Education_Level { get; set; }

            [ColumnName(@"Mother's Highest Education Level")]
            public float Mother_s_Highest_Education_Level { get; set; }

            [ColumnName(@"Actual Result")]
            public string Actual_Result { get; set; }

            [ColumnName(@"Class Status")]
            public bool Class_Status { get; set; }

            [ColumnName(@"Average Previous Marks")]
            public float Average_Previous_Marks { get; set; }

            [ColumnName(@"Study Hours")]
            public float Study_Hours { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for OrientedMusic.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Father's Highest Education Level")]
            public float Father_s_Highest_Education_Level { get; set; }

            [ColumnName(@"Mother's Highest Education Level")]
            public float Mother_s_Highest_Education_Level { get; set; }

            [ColumnName(@"Actual Result")]
            public uint Actual_Result { get; set; }

            [ColumnName(@"Class Status")]
            public float Class_Status { get; set; }

            [ColumnName(@"Average Previous Marks")]
            public float Average_Previous_Marks { get; set; }

            [ColumnName(@"Study Hours")]
            public float Study_Hours { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("OrientedMusic.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
